name: Maven CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Install external jars (if any)
        if: ${{ hashFiles('libs/*.jar') != '' }}
        run: |
          mvn -q install:install-file -Dfile=libs/gpsUtil.jar       -DgroupId=gpsUtil       -DartifactId=gpsUtil       -Dversion=1.0.0 -Dpackaging=jar
          mvn -q install:install-file -Dfile=libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
          mvn -q install:install-file -Dfile=libs/TripPricer.jar    -DgroupId=tripPricer    -DartifactId=tripPricer    -Dversion=1.0.0 -Dpackaging=jar

      - name: Build & Test (timed)
        run: |
          start=$(date +%s)
          mvn -B -ntp '-Dtest=!TestPerformance' clean verify
          end=$(date +%s)
          echo " Build & Test : $((end-start))s" >> $GITHUB_STEP_SUMMARY 

      - name: Upload artifacts (jar + test reports)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tourguide-artifacts
          path: |
            target/*.jar
            **/target/surefire-reports/**

  perf:
    name: Performance Tests
    if: ${{ github.event_name == 'workflow_dispatch' }}   # lance seulement à la demande
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      matrix:
        userCount: [100, 1000, 10000]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Install external jars (if any)
        if: ${{ hashFiles('libs/*.jar') != '' }}
        run: |
          mvn -q install:install-file -Dfile=libs/gpsUtil.jar       -DgroupId=gpsUtil       -DartifactId=gpsUtil       -Dversion=1.0.0 -Dpackaging=jar
          mvn -q install:install-file -Dfile=libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
          mvn -q install:install-file -Dfile=libs/TripPricer.jar    -DgroupId=tripPricer    -DartifactId=tripPricer    -Dversion=1.0.0 -Dpackaging=jar

      - name: Run TestPerformance (userCount=${{ matrix.userCount }})
        run: mvn -B -ntp -Dtest=TestPerformance -DuserCount=${{ matrix.userCount }} test
